### ISSUE TITLE
Add China region for s3 and ec2

### ISSUE THREAD

**Issue by psu1025** [elasticsearch/elasticsearch-cloud-aws#156]
please add china region.

china region name is cn-north-1.

**Comment by dadoonet** [comment]
@psu1025 I think the patch I wrote a month ago won't work actually. 
China is not part of the [S3 regions](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) but part of [Isolated Regions](http://docs.aws.amazon.com/general/latest/gr/isolated_regions.html).

The patch I wrote uses for S3 `s3-cn-north-1.amazonaws.com` which is wrong because in that case the end point is `s3.cn-north-1.amazonaws.com.cn`. 

Reopening to send a new fix.

**Comment by rbraley** [comment]
+1 this is blocking us

**Comment by dadoonet** [comment]
Closed by 4c02a017b43539d26964b639a71bf589cba1f72c
